language: python
python:
  - "2.7"
  - "3.4"
addons:
  postgresql: "9.1"
env:
  PYTHONPATH='.'
virtualenv:
  system_site_packages: true
install: "pip install -r requirements.txt"
before_script:
  - psql -U postgres -c 'CREATE DATABASE mdsdb;'
  - psql -U postgres -c "CREATE EXTENSION postgis" -d mdsdb
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d mdsdb
script: python manage.py test