language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
services:
  - rabbitmq
env:
  PYTHONPATH='.'
virtualenv:
  system_site_packages: true
install: "pip install -r requirements.txt"
before_script:
  - sudo apt-get install -qq python-gdal
  - sudo apt-get install -qq postgis
  - psql -U postgres -c "CREATE DATABASE mdsdb;"
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - psql -U postgres -c "CREATE EXTENSION postgis_topology"
  - python manage.py start_celery
script: python manage.py test